server:
  port: 7001
#  servlet:
#    context-path: /eureka
# 访问监控页面地址 http://localhost:7001




#Eureka配置
eureka:
  instance:
    hostname: localhost # Eureka服务端实例的名字
  client:
    register-with-eureka: false  # 表示是否将自己注册到Eureka Server
    fetch-registry: false # 表示是否从Eureka Server获取注册的服务信息 默认为true
    service-url: # 监控页面地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/